class states():
	states = {
       'Alaska': 'AK',
       'Alabama': 'AL',
       'Arkansas': 'AR',
       'American Samoa': 'AS',
       'Arizona': 'AZ',
       'California': 'CA',
       'Colorado': 'CO',
       'Connecticut': 'CT',
       'District of Columbia': 'DC',
       'Delaware': 'DE',
       'Florida': 'FL',
       'Georgia': 'GA',
       'Guam': 'GU',
       'Hawaii': 'HI',
       'Iowa': 'IA',
       'Idaho': 'ID',
       'Illinois': 'IL',
       'Indiana': 'IN',
       'Kansas': 'KS',
       'Kentucky': 'KY',
       'Louisiana': 'LA',
       'Massachusetts': 'MA',
       'Maryland': 'MD',
       'Maine': 'ME',
       'Michigan': 'MI',
       'Minnesota': 'MN',
       'Missouri': 'MO',
       'Northern Mariana Islands': 'MP',
       'Mississippi': 'MS',
       'Montana': 'MT',
       'National': 'NA',
       'North Carolina': 'NC',
       'North Dakota': 'ND',
       'Nebraska': 'NE',
       'New Hampshire': 'NH',
       'New Jersey': 'NJ',
       'New Mexico': 'NM',
       'Nevada': 'NV',
       'New York': 'NY',
       'Ohio': 'OH',
       'Oklahoma': 'OK',
       'Oregon': 'OR',
       'Pennsylvania': 'PA',
       'Puerto Rico': 'PR',
       'Rhode Island': 'RI',
       'South Carolina': 'SC',
       'South Dakota': 'SD',
       'Tennessee': 'TN',
       'Texas': 'TX',
       'Utah': 'UT',
       'Virginia': 'VA',
       'Virgin Islands': 'VI',
       'Vermont': 'VT',
       'Washington': 'WA',
       'Wisconsin': 'WI',
       'West Virginia': 'WV',
       'Wyoming': 'WY',
       'AK': 'AK',
       'AL': 'AL',
       'AR': 'AR',
       'AS': 'AS',
       'AZ': 'AZ',
       'CA': 'CA',
       'CO': 'CO',
       'CT': 'CT',
       'DC': 'DC',
       'DE': 'DE',
       'FL': 'FL',
       'GA': 'GA',
       'GU': 'GU',
       'HI': 'HI',
       'IA': 'IA',
       'ID': 'ID',
       'IL': 'IL',
       'IN': 'IN',
       'KS': 'KS',
       'KY': 'KY',
       'LA': 'LA',
       'MA': 'MA',
       'MD': 'MD',
       'ME': 'ME',
       'MI': 'MI',
       'MN': 'MN',
       'MO': 'MO',
       'MP': 'MP',
       'MS': 'MS',
       'MT': 'MT',
       'NA': 'NA',
       'NC': 'NC',
       'ND': 'ND',
       'NE': 'NE',
       'NH': 'NH',
       'NJ': 'NJ',
       'NM': 'NM',
	   'NS': 'NS',
       'NV': 'NV',
       'NY': 'NY',
       'OH': 'OH',
       'OK': 'OK',
	   'ON': 'ON',
       'OR': 'OR',
       'PA': 'PA',
       'PR': 'PR',
       'RI': 'RI',
       'SC': 'SC',
       'SD': 'SD',
       'TN': 'TN',
       'TX': 'TX',
       'UT': 'UT',
       'VA': 'VA',
       'VI': 'VI',
       'VT': 'VT',
       'WA': 'WA',
       'WI': 'WI',
       'WV': 'WV',
       'WY': 'WY'
	}
